export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSS = 'AUTH_SUCCESSS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const POST_NETWORTH_START = 'POST_NETWORTH_START';
export const POST_NETWORTH_SUCCESS = 'POST_NETWORTH_SUCCESS';
export const POST_NETWORTH_FAIL = 'POST_NETWORTH_FAIL';

export const START_FORM = 'START_FORM';
