export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESSS = 'AUTH_SUCCESSS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const POST_NETWORTH_START = 'POST_NETWORTH_START';
export const POST_NETWORTH_SUCCESS = 'POST_NETWORTH_SUCCESS';
export const POST_NETWORTH_FAIL = 'POST_NETWORTH_FAIL';

export const GET_CURRENT_NETWORTH_START = 'GET_CURRENT_NETWORTH_START';
export const GET_CURRENT_NETWORTH_SUCCESS = 'GET_CURRENT_NETWORTH_SUCCESS';
export const GET_CURRENT_NETWORTH_FAIL = 'GET_CURRENT_NETWORTH_FAIL';

export const GET_ALL_NETWORTH_START = 'GET_ALL_NETWORTH_START';
export const GET_ALL_NETWORTH_SUCCESS = 'GET_ALL_NETWORTH_SUCCESS';
export const GET_ALL_NETWORTH_FAIL = 'GET_ALL_NETWORTH_FAIL';

export const DELETE_NETWORTH_START = 'DELETE_NETWORTH_START';
export const DELETE_NETWORTH_SUCCESS = 'DELETE_NETWORTH_SUCCESS';
export const DELETE_NETWORTH_FAIL = 'DELETE_NETWORTH_FAIL';

export const GET_NETWORTH_START = 'GET_NETWORTH_START';
export const GET_NETWORTH_FAIL = 'GET_NETWORTH_FAIL';
export const GET_NETWORTH_SUCCESS = 'GET_NETWORTH_SUCCESS';

export const SIGNUP_START = 'SINGUP_START';
export const SIGNUP_SUCCESS = 'SINGUP_SUCCESS';
export const SIGNUP_FAIL = 'SINGUP_FAIL';

export const START_FORM = 'START_FORM';
